import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

// import ThemeContextProvider from "@/contexts/themeContext";
import Theme from "@/providers/Theme";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="light transition-all duration-300" style={{colorScheme: "light"}}>
      <body className={inter.className}>
        <Theme>
          <Navbar />
          {children}
        </Theme>
      </body>
    </html>
  );
}
