import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import NavbarMain from "@/components/navbars/NavbarMain";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className} id="body">
        <NavbarMain />
        <div className="mb-20"></div>
        {children}
      </body>
    </html>
  );
}
